project_id = "taimpwfhxqenrkumbkng"

[auth]
enable_signup = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template = {
  signup = {
    webhook = "https://taimpwfhxqenrkumbkng.supabase.co/functions/v1/auth-email-webhook"
  }
}

[functions.crypto-details]
verify_jwt = false

[functions.fetch-btc-data]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.voltmarket-chat]
verify_jwt = false

[functions.meta-proxy]
verify_jwt = false

[functions.auth-email-webhook]
verify_jwt = false

[functions.get-mapbox-config]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false