-- Drop existing RLS policies that conflict
DROP POLICY IF EXISTS "Users can view their own voltmarket profile" ON public.voltmarket_profiles;
DROP POLICY IF EXISTS "Users can create their own voltmarket profile" ON public.voltmarket_profiles;
DROP POLICY IF EXISTS "Users can update their own voltmarket profile" ON public.voltmarket_profiles;
DROP POLICY IF EXISTS "Anyone can view active listings" ON public.voltmarket_listings;
DROP POLICY IF EXISTS "Users can create listings" ON public.voltmarket_listings;
DROP POLICY IF EXISTS "Sellers can update own listings" ON public.voltmarket_listings;
DROP POLICY IF EXISTS "Sellers can update their listings" ON public.voltmarket_listings;
DROP POLICY IF EXISTS "Anyone can view listing images" ON public.voltmarket_listing_images;
DROP POLICY IF EXISTS "Listing owners can manage their images" ON public.voltmarket_listing_images;
DROP POLICY IF EXISTS "Users can view conversations they're in" ON public.voltmarket_conversations;
DROP POLICY IF EXISTS "Users can view messages they're involved in" ON public.voltmarket_messages;
DROP POLICY IF EXISTS "Users can manage VoltMarket contact messages" ON public.voltmarket_contact_messages;
DROP POLICY IF EXISTS "Users can view LOIs they're involved in" ON public.voltmarket_lois;
DROP POLICY IF EXISTS "Buyers can create LOIs" ON public.voltmarket_lois;
DROP POLICY IF EXISTS "Sellers can update LOI status" ON public.voltmarket_lois;
DROP POLICY IF EXISTS "Users can view their own documents" ON public.voltmarket_documents;
DROP POLICY IF EXISTS "Users can create documents" ON public.voltmarket_documents;
DROP POLICY IF EXISTS "Users can update their documents" ON public.voltmarket_documents;
DROP POLICY IF EXISTS "Users can delete their documents" ON public.voltmarket_documents;
DROP POLICY IF EXISTS "Users can view due diligence they're involved in" ON public.voltmarket_due_diligence;
DROP POLICY IF EXISTS "Users can view their analytics" ON public.voltmarket_analytics;
DROP POLICY IF EXISTS "Users can manage their GridBazaar profile" ON public.gridbazaar_profiles;
DROP POLICY IF EXISTS "Public can create access requests" ON public.access_requests;
DROP POLICY IF EXISTS "Public can view access requests" ON public.access_requests;
DROP POLICY IF EXISTS "Public can create site access requests" ON public.site_access_requests;
DROP POLICY IF EXISTS "Public can view site access requests" ON public.site_access_requests;
DROP POLICY IF EXISTS "Users can view all properties" ON public.properties;
DROP POLICY IF EXISTS "Users can create properties" ON public.properties;
DROP POLICY IF EXISTS "Users can update their own properties" ON public.properties;
DROP POLICY IF EXISTS "Users can delete their own properties" ON public.properties;
DROP POLICY IF EXISTS "Users can view all scraped properties" ON public.scraped_properties;
DROP POLICY IF EXISTS "Authenticated users can create scraped properties" ON public.scraped_properties;
DROP POLICY IF EXISTS "Authenticated users can view verified sites" ON public.verified_heavy_power_sites;
DROP POLICY IF EXISTS "Users can manage their verified sites" ON public.verified_heavy_power_sites;
DROP POLICY IF EXISTS "Users can manage their scan sessions" ON public.site_scan_sessions;
DROP POLICY IF EXISTS "Authenticated users can create city power analysis" ON public.city_power_analysis;
DROP POLICY IF EXISTS "Users can view all city power analysis" ON public.city_power_analysis;
DROP POLICY IF EXISTS "Authenticated users can view intel results" ON public.industry_intel_results;
DROP POLICY IF EXISTS "Authenticated users can create substations" ON public.substations;
DROP POLICY IF EXISTS "Users can view all substations" ON public.substations;
DROP POLICY IF EXISTS "Anyone can view energy markets" ON public.energy_markets;
DROP POLICY IF EXISTS "Authenticated users can create energy market data" ON public.energy_markets;
DROP POLICY IF EXISTS "Anyone can view energy rates" ON public.energy_rates;
DROP POLICY IF EXISTS "Authenticated users can view AI analysis" ON public.ai_company_analysis;
DROP POLICY IF EXISTS "Authenticated users can view distress alerts" ON public.distress_alerts;
DROP POLICY IF EXISTS "Authenticated users can view industry intelligence" ON public.industry_intelligence;
DROP POLICY IF EXISTS "Authenticated users can view company assets" ON public.company_real_estate_assets;
DROP POLICY IF EXISTS "Users can view all companies" ON public.companies;
DROP POLICY IF EXISTS "Authenticated users can create companies" ON public.companies;
DROP POLICY IF EXISTS "Users can view their own alerts" ON public.alerts;
DROP POLICY IF EXISTS "Users can create alerts" ON public.alerts;
DROP POLICY IF EXISTS "Users can update their own alerts" ON public.alerts;
DROP POLICY IF EXISTS "Users can delete their own alerts" ON public.alerts;
DROP POLICY IF EXISTS "Users can manage their alert preferences" ON public.user_alert_preferences;
DROP POLICY IF EXISTS "Users can manage their BTC calculations" ON public.btc_roi_calculations;
DROP POLICY IF EXISTS "Authenticated users can create volt scores" ON public.volt_scores;
DROP POLICY IF EXISTS "Users can view all volt scores" ON public.volt_scores;
DROP POLICY IF EXISTS "Users can create their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can manage their requests" ON public.voltmarket_nda_requests;