// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taimpwfhxqenrkumbkng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhaW1wd2ZoeHFlbnJrdW1ia25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjA0NTMsImV4cCI6MjA2ODE5NjQ1M30.-nUxIrxNJ9kftuHOOc8DwVQd-eIfsWztp2mjYYMS_BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});